### ISSUE TITLE
ひとこと送信対応

### ISSUE THREAD

**Issue by shin0O** [kan/million-timer#2]
完了 までに数回画面遷移あり。

**Comment by kan** [comment]
送信まで自動でやっちゃうのは若干おっかないですね(今のところチェッカーが操作までしてるやつはないので)。便利なのは間違いないですがw (逆にありなら劇場とかもオート実行モードがあっても良さそう)

**Comment by shin0O** [comment]
さすがに真っ黒なので「送信可能だよー(o・∇・o)」 でもいいんじゃないかなあと

**Comment by kan** [comment]
あい、そんな感じで実装してみましたw
